version: '3.8'

services:
  app:
    container_name: express-typescript
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    #      - /usr/src/app/node_modules # Remove this if you have pure JS dependencies
    ports:
      - "3000:3000"
